# "Dust" troopers

# Tier 1

- type: startingGear
  id: MobHumanoidDScrapGearRangedRT1
  equipment:
    shoes: ClothingShoesLinenwrap
    gloves: ClothingHandsRepeater
    pocket2: DrinkMREFlask

- type: startingGear
  id: MobHumanoidDScrapGearRangedST1
  equipment:
    shoes: ClothingShoesLinenwrap
    gloves: ClothingHandsSVS42
    pocket2: DrinkMREFlask

- type: startingGear
  id: MobHumanoidDScrapGearMeleeST1
  equipment:
    shoes: ClothingShoesLinenwrap
    gloves: ClothingHandsMachete
    pocket2: DrinkMREFlask

- type: startingGear
  id: MobHumanoidDScrapGearRangedShilovPistolT1
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsShilov
    pocket2: DrinkMREFlask

- type: startingGear
  id: MobHumanoidDScrapGearRangedM44UT1
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsM44U
    pocket2: DrinkMREFlask

# Special T1

- type: startingGear
  id: MobHumanoidDScrapGearRangedRLiwT1
  equipment:
    shoes: ClothingShoesLinenwrap
    gloves: ClothingHandsRepeater
    pocket2: DrinkLiwerBottleFull

- type: startingGear
  id: MobHumanoidDScrapGearRangedSLiwT1
  equipment:
    shoes: ClothingShoesLinenwrap
    gloves: ClothingHandsSVS42
    pocket2: DrinkLiwerBottleFull

- type: startingGear
  id: MobHumanoidDScrapGearRangedM44PUT1
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsM44PU
    pocket2: DrinkMREFlask

# Tier 2

- type: startingGear
  id: MobHumanoidDScrapGearRangedTT2
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsTypewriter

- type: startingGear
  id: MobHumanoidDScrapGearRangedASUT2
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsASU

- type: startingGear
  id: MobHumanoidDScrapGearRangedAST2
  equipment:
    shoes: ClothingShoesBootsCowboyBrown
    gloves: ClothingHandsAS

# Special T2

- type: startingGear
  id: MobHumanoidDScrapGearRangedASUT2Air
  equipment:
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsASUAlt
    pocket2: MagazinePackedRiflefilled


- type: startingGear
  id: MobHumanoidDScrapGearRangedASSAir
  equipment:
    shoes: ClothingShoesBootsJack
    gloves: ClothingHandsASS
    pocket2: MagazinePackedRiflefilled

# Tier 3

- type: startingGear
  id: MobHumanoidDScrapAirbornCaptainT3
  equipment:
    head: ClothingHeadHatDustBeret
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCombat
    pocket1: MagazinePackedDrumRifleEmpty
    pocket2: MagazinePackedDrumRiflelUranium
    outerClothing: ClothingOuterArmorBasicSlim
    suitstorage: WeaponScrapLightMachineGunRPS55
  inhand:
    - CombatKnife

- type: startingGear
  id: MobHumanoidDScrapAirbornCaptainT3Alt
  equipment:
    head: ClothingHeadHatDustBeret
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesEyepatch
    gloves: ClothingHandsRPS
    pocket1: MagazinePackedDrumRiflelUranium
    pocket2: MagazinePackedDrumRiflelUranium
    outerClothing: ClothingOuterArmorBasicSlim

- type: startingGear
  id: MobHumanoidDScrapRaiderT3Alt
  equipment:
    head: ClothingHeadHatHoodScrapCloak
    shoes: ClothingShoesBootsPilot
    mask: ClothingMaskGasDustRaider
    gloves: ClothingHandsShilovRaider

- type: startingGear
  id: MobHumanoidDScrapRaiderT3
  equipment:
    head: ClothingHeadHatHoodScrapCloak
    shoes: ClothingShoesBootsPilot
    mask: ClothingMaskGasDustRaider
    gloves: ClothingHandsDeserterRaider
    pocket1: MagazinePackedLMGIncendiary
    outerClothing: ClothingOuterArmorHeavyScrapRaider
    suitstorage: WeaponScrapLightMachineGunDeserter



